In [1]:
# It’s a Python-based scientific computing package targeted at two sets of audiences:

# A replacement for NumPy to use the power of GPUs
# a deep learning research platform that provides maximum flexibility and speed

In [2]:
from __future__ import print_function
import torch

In [5]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 2)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [-6.8208e-31,  3.0873e-41],
        [ 0.0000e+00,  0.0000e+00],
        [-1.1354e-29,  3.0873e-41]])


In [6]:
# Construct a randomly initialized matrix:

x = torch.rand(5, 3)
print(x)

tensor([[0.7826, 0.0132, 0.6605],
        [0.6219, 0.6612, 0.3061],
        [0.1776, 0.6316, 0.3281],
        [0.4487, 0.1839, 0.0420],
        [0.4341, 0.2092, 0.5037]])


In [8]:
# Construct a matrix filled zeros and of dtype long:

x = torch.zeros(5, 3,  dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# Construct a tensor(vector) directly from data:

x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
#or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)  

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8411,  0.5586, -1.1086],
        [ 0.5618, -0.6605,  0.3566],
        [-0.1675,  0.6962,  0.5914],
        [-0.5319, -0.1195, -0.3303],
        [-0.1961,  0.5389,  0.2783]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [15]:
# Operations
# There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.


x = torch.rand(5, 3)
y = torch.rand(5, 3)

z = torch.add(x, y)
print(z)

tensor([[0.8878, 1.0115, 1.5093],
        [1.7459, 1.2933, 0.7120],
        [0.4530, 1.8721, 0.3731],
        [1.0773, 1.2559, 1.5225],
        [0.8214, 1.1837, 1.1360]])


In [16]:

x = torch.rand(5, 4)
y = torch.rand(5, 3)

z = torch.add(x, y)
print(z)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1